# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1380, 849)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_pos_view = QtWidgets.QLabel(self.centralwidget)
        self.label_pos_view.setMinimumSize(QtCore.QSize(1024, 786))
        self.label_pos_view.setText("")
        self.label_pos_view.setObjectName("label_pos_view")
        self.verticalLayout_2.addWidget(self.label_pos_view)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_camera_view = QtWidgets.QLabel(self.centralwidget)
        self.label_camera_view.setMinimumSize(QtCore.QSize(326, 174))
        self.label_camera_view.setText("")
        self.label_camera_view.setObjectName("label_camera_view")
        self.verticalLayout.addWidget(self.label_camera_view)
        self.label_detect_view = QtWidgets.QLabel(self.centralwidget)
        self.label_detect_view.setText("")
        self.label_detect_view.setObjectName("label_detect_view")
        self.verticalLayout.addWidget(self.label_detect_view)
        self.widget_unknown_input = QtWidgets.QWidget(self.centralwidget)
        self.widget_unknown_input.setEnabled(False)
        self.widget_unknown_input.setObjectName("widget_unknown_input")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_unknown_input)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.widget_unknown_input)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.widget_unknown_input)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.widget_unknown_input)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.verticalLayout.addWidget(self.widget_unknown_input)
        self.labe_info = QtWidgets.QLabel(self.centralwidget)
        self.labe_info.setObjectName("labe_info")
        self.verticalLayout.addWidget(self.labe_info)
        self.verticalLayout.setStretch(0, 4)
        self.verticalLayout.setStretch(1, 2)
        self.verticalLayout.setStretch(3, 9)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1380, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "이름을 입력해 주세요 "))
        self.pushButton.setText(_translate("MainWindow", "등록"))
        self.labe_info.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">회원 ID : 12345</span></p><p><span style=\" font-size:12pt;\">지난 번 주문 : 아메리카노</span></p><p><span style=\" font-size:12pt;\">오늘의 맞춤 추천 메뉴 : 레몬티</span></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p><p><br/></p></body></html>"))

